version: '3.8'

services:
  web:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/app
      - ./docker/php/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/logs:/var/log/nginx
    depends_on:
      - mysql
    networks:
      - library-network

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library_db
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./app/logs:/var/log/mysql
    networks:
      - library-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - library-network

volumes:
  mysql_data:

networks:
  library-network:
    driver: bridge